### ISSUE TITLE
Consider code of conduct

### ISSUE THREAD

**Issue by ctrlcctrlv** [libsixel/libsixel#21]
Recent incidents of trolling around #20 have led me to consider whether or not a Code of Conduct is worthwhile for this project.

I've contributed to a lot of open source projects over the years, both those with CoC's and those without. Personally, I find CoC's to be beneficial. But, this is a sensitive issue. So, what do those who are currently working on this or wish to want?

I think this project is the first one that's become large enough and that I've been in any kind of decision making role to have this discussion.

**Comment by dankamongmen** [comment]
if you're asking my opinion, i have never thought much of Codes of Conduct, but i certainly won't protest adding one.

i've gotta say, that interaction was a rather shocking one to me -- i hack open source all day, every day, just about, and don't see stuff like that very often.

either way, i'd either add one and close this bug, or don't add one and close this bug, because it's exactly this kind of non-technological thing that people will drop in and ventilate on. =]

**Comment by ctrlcctrlv** [comment]
@dankamongmen Good to see you online. Do you mind sending me the sixel-encoded graphic mentioned at saitoha#149? I think I fixed the _decoder_ and have a patch ready for PR, but I have no way to test it. The _encoder_ is still b0rked. I'm treating them as separate issues.

**Comment by ctrlcctrlv** [comment]
My patch fixes the changing palettes issue in the decoder as well. I discovered it was a two for one deal: the root problem is the same in both cases: clumsily juggling palettes.

**Comment by ctrlcctrlv** [comment]
I mean I suppose I could hand-encode a transparent background Sixel, but it'd be a lot easier just to have one on hand as a test case :joy:

**Comment by ctrlcctrlv** [comment]
Nevermind, figured it out. It's really ugly, much worse than your test case, but behold, the first transparent output from libsixel! :-D

![image](https://user-images.githubusercontent.com/838783/122286495-e9b49980-cebd-11eb-895b-bf1326a9670b.png)
